version: "3.4"
services:
  # openvpn:
  #   container_name: openvpn
  #   image: dperson/openvpn-client:latest
  #   cap_add:
  #     - net_admin # required to modify network interfaces
  #   restart: unless-stopped
  #   volumes:
  #     - /dev/net:/dev/net:z # tun device
  #     - ${CONFIG}/config/vpn:/vpn # OpenVPN configuration
  #   security_opt:
  #     - label:disable
  #   ports:
  #     - 9091:9091 # Transmission web UI
  #     - 51413:51413 # Transmission bittorrent daemon
  #     - 51413:51413/udp # Transmission bittorrent daemon
  #     - 8112:8112 # port for deluge web UI to be reachable from local network
  #   command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    network_mode: ${NETWORKMODE} # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${CONFIG}/config/transmission:/config # config files
    ports:
      - 9091:9091 # Transmission web UI
      - 51413:51413 # Transmission bittorrent daemon
      - 51413:51413/udp # Transmission bittorrent daemon

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: ${NETWORKMODE} # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${CONFIG}/config/deluge:/config # config files
    ports:
      - 8112:8112
      - 5846:5846

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG}/config/jackett:/config # config files
    ports:
      - 9117:9117

  # nzbget:
  #   container_name: nzbget
  #   image: linuxserver/nzbget:latest
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #   volumes:
  #     - ${ROOT}/downloads:/downloads # download folder
  #     - ${ROOT}/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 7878:7878

  # plex-server:
  #   container_name: plex-server
  #   image: plexinc/pms-docker:latest
  #   restart: unless-stopped
  #   environment:
  #     - TZ=${TZ} # timezone, defined in .env
  #   network_mode: host
  #   volumes:
  #     - ${ROOT}/config/plex/db:/config # plex database
  #     - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
  #     - ${ROOT}/complete:/data # media library

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:nightly
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - UMASK=002
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/config/prowlarr:/config # config files
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
    ports:
      - 9696:9696
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${CONFIG}/config/bazarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/complete/tv:/tv # tv shows folder
    ports:
      - 6767:6767
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:nightly
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG}/config/lidarr:/config # config files
      - ${ROOT}/complete/music:/music # music folder
      - ${ROOT}/downloads:/downloads # download shows folder
    ports:
      - 8686:8686
  readarr:
    container_name: readarr
    image: linuxserver/readarr:nightly
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG}/config/readarr:/config # config files
      - ${ROOT}/complete/books:/books # music folder
      - ${ROOT}/downloads:/downloads # download shows folder
    ports:
      - 8787:8787